### PR TITLE
Update to 1.0.1-a.6

### PR DESCRIPTION
**Pull request by ch4og**

### CODE REVIEW

**Comment by clementpoiret** [comment]
You are literally the fastest person alive ahahah! Thanks a lot for taking the time to update zen :)

**Comment by TheRobo-13** [comment]
appreciate you making the PR, was gonna try figuring it out


i'm wondering how updating the flake works

i see that in the `flake.nix` the SHA256 needs to be changed for the generic and specific release

**Comment by ch4og** [comment]
> i see that in the `flake.nix` the SHA256 needs to be changed for the generic and specific release

https://nix.dev/manual/nix/2.18/command-ref/nix-prefetch-url.html

```
[ch@nixpc:~]$ nix-prefetch-url github.com/zen-browser/desktop/releases/download/1.0.1-a.6/zen.linux-specific.tar.bz2 --unpack
path is '/nix/store/lxsh8v0y6zfv3hc2m6cbg0253yh64lin-zen.linux-specific.tar.bz2'
0jkzdrsd1qdw3pwdafnl5xb061vryxzgwmvp1a6ghdwgl2dm2fcz
```

**Comment by chakibchemso** [comment]
bro at this rate, ive just switched to your repo for faster than light updates. thx

**Comment by Icy-Thought** [comment]
We can always go the nix-community route if y'all are up for it. :shrug:

**Pull request merged**
