### PR TITLE
Update to 1.0.1-a.5

### PR DESCRIPTION
**Pull request by ch4og**
Newest version & lock update

### CODE REVIEW

**Review by Titaniumtown — APPROVED** [review]
LGTM

**Comment by TheRobo-13** [comment]
It's been almost 3 days, how long until it will be updated?

**Comment by Icy-Thought** [comment]
No hate, but maybe we should move the project to nixos-community and have more maintainers be able to merge stuff.
EDIT: pre-edit made it sound like OP was not a qualified maintainer. Removed that bit. They are, as we can see for ourselves. :)

**Comment by Soliprem** [comment]
Agree with the move to nixos-community. Keeping up with updates of such a fast-moving project shouldn't be expected of a single person. Where can it be proposed?

**Comment by ibrokemypie** [comment]
> Agree with the move to nixos-community. Keeping up with updates of such a fast-moving project shouldn't be expected of a single person. Where can it be proposed?

There's already a packaging request for it [here](https://github.com/NixOS/nixpkgs/issues/327982), someone just needs to create a pr.

**Comment by Icy-Thought** [comment]
Doesn't creating a PR to nixpkgs make it a nixpkgs package and not a [nix-community](https://github.com/nix-community) project? And I don't think the package would be accepted because of its alpha stage + it takes time to push/build the package for all the different branches.

EDIT: 
https://github.com/orgs/nix-community/discussions is where all the requests takes place.
@MarceColl any interest in making this project a nix-community one?

**Comment by MarceColl** [comment]
Sorry! Was on a company offsite last week and didn't log into GH at all, merged now.

I'm fine with moving it to a nix-community repo

**Comment by Icy-Thought** [comment]
Welcome back! And thanks for merging the PR! :)
If you are interested, just create a new discussion in the nix-community community.

**Pull request merged**
