### PR TITLE
Update to 1.0.1-a.22

### PR DESCRIPTION
**Pull request by ch4og**
https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.17

### CODE REVIEW

**Comment by omarcresp** [comment]
hey @ch4og did you had issues with the prefecth url? it didnt worked for my this way:
```bash
$ nix-prefetch-url --type sha256 https://github.com/zen-browser/desktop/releases/download/1.0.1-a.7/zen.linux-specific.tar.bz2
path is '/nix/store/ak8qmkw0ksi19q5di40hkgywnqx5w4p4-zen.linux-specific.tar.bz2'
1ll7qhcr4sii4lnacfzf68y6c0vm26is72k9jsrz57srjvzb4cvk
```
the hash was incorrect, did you got the sha256 in other way?

**Comment by ch4og** [comment]
> the hash was incorrect, did you got the sha256 in other way?

I personally don't use nix-prefetch-url but it can be used.


Your arguments are wrong to fetch from an archive

```
nix-prefetch-url(1)                          General Commands Manual                         nix-prefetch-url(1)

Name
       nix-prefetch-url - copy a file from a URL into the store and print its hash
       ....
       
Options
       ...

       •  --unpack
          Unpack the archive (which must be a tarball or zip file) and add the result to the Nix store. The  re‐
          sulting hash can be used with functions such as Nixpkgs’s fetchzip or fetchFromGitHub.

````

You should use 
`nix-prefetch-url --type sha256 --unpack https://github.com/zen-browser/desktop/releases/download/1.0.1-a.7/zen.linux-specific.tar.bz2`

**Comment by omarcresp** [comment]
oh Thanks you, that was a missing part. I have use nix prefetch for appImage before. didnt knew unpack was needed when fetching archives

**Comment by andy-novikov** [comment]
so.. why isn't this merged yet?
switching to `ch4og` for now as the update notifications getting me.

**Comment by Titaniumtown** [comment]
Is there any blockers here? LGTM.

**Review by pinage404 — APPROVED** [review]
works great for me on NixOS x86_64

**Review by chakibchemso — APPROVED** [review]

**Comment by luisnquin** [comment]
This is an important contribution and it seems the current owner is no longer interested in maintaining it so I just created a fork of this project for those who really want more activity.

You can find it at https://github.com/0xc000022070/zen-browser-flake.

**Comment by Icy-Thought** [comment]
@luisnquin there is already a fork that is being maintained BTW. And Ch40g is the one keeping it alive! (Thanks!!)
https://github.com/ch4og/zen-browser-flake

**Comment by luisnquin** [comment]
@Icy-Thought thanks for the suggestion. But that repository does not have the changes proposed for this one and it seems that new commits are limited to the update version (I think that area should be automated, which is not the case for that repository).

**Comment by chakibchemso** [comment]
@luisnquin There's actually a ci automated fork at https://github.com/omarcresp/zen-browser-flake

**Comment by luisnquin** [comment]
@chakibchemso nice!

**Comment by Icy-Thought** [comment]
Damn we have many forks and this project is not that old yet. Why not choose one and go to nix-community instead?

**Comment by pinage404** [comment]
Why do we need another repository in a flake and not simply in nixpkgs ?

**Comment by omarcresp** [comment]
I think macOS support is required for nixpkgs (not sure), I’m working on it for the flake. Also not sure if we can automate updates in nixpkgs, if not I’ll rather keep in the flake due to the rapid iteration that the browser has in this early stage. I use zen as my daily driver in both my work and personal computer, so having the ci updating every hour is should to have for me.

**Comment by ch4og** [comment]
Nix states that anything that can be built from source should be. Implementation of this flake is using prebuilt binaries so it won't work. Currently there is WIP package request that needs help https://github.com/NixOS/nixpkgs/issues/327982

**Comment by ch4og** [comment]
> Also not sure if we can automate updates in nixpkgs, if not I’ll rather keep in the flake due to the rapid iteration that the browser has in this early stage.

There is an easy way that creates PRs automatically but master merges to nixos-unstable not very often and PR should be merged itself too, so there is no way to make fast enough updates in nixpkgs

**Comment by ch4og** [comment]
Best solution possible that keeps up with updates is creating flake that builds from source in original zen browser repo

**Pull request closed without merging**
